var shoes = "Addidas";
console.log("Are Shoes == Addidas ?,I predict ".concat(shoes == "Addidas"));
var car = "Buggati";
console.log("2- ".concat(car == "Buggati"));
var fruit = "Watermelon";
console.log("3- ".concat(fruit == "Apple"));
var school = "Crescent School";
console.log("4- ".concat(school == "Federal School"));
var laptop = "Lenovo";
console.log("5- ".concat(laptop == "Lenovo"));
var chair = "Yellow";
console.log("6- ".concat(chair == "yellow"));
var Standard = "Inter";
console.log("7- ".concat(Standard == "Inter"));
var teacher = "Sir Hashir";
console.log("8- ".concat(teacher == "Sir Younus"));
var vegetable = "Beetroot";
console.log("9- ".concat(vegetable == "Beetroot"));
var color = "Green";
console.log("10- ".concat(color == "green"));
